[project]
name = "AoC_2025"
version = "0.1.0"
description = "Minimal environment for Advent of Code 2025 solutions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coloredlogs>=15.0.1",
    "ipykernel>=7.1.0",
    "numpy>=2.3.5",
]
